# Default values for bansira-banking
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

helloworld:
  namespace: default
  image:
    name: tutum/hello-world
    tag: latest
    pullPolicy: IfNotPresent
  service:
    ingressClass: internal-ingress

nameOverride: ""
replicaCount: 1